### ISSUE TITLE
header styling not working

### ISSUE THREAD

**Issue by mohmmadmoussa1988** [yeswanth/react-native-dynamic-tab-view#12]
Hello,

Im trying to change the color of text inside tabs, but they are unchangeable (always white) and cant give it 100% width .

<img width="383" alt="Screen Shot 2019-06-13 at 9 51 47 PM" src="https://user-images.githubusercontent.com/37548159/59459472-89e60c80-8e25-11e9-8510-031842b28fcf.png">
I need to make the header with full width grey

**Comment by mohmmadmoussa1988** [comment]
I need to make the header with full width grey

**Comment by yeswanth** [comment]
HI @mohmmadmoussa1988 Did your issue get resolved or do you need some help with it?

**Comment by yeswanth** [comment]
Thanks for reporting. I published a new version `1.0.7`. 
* You can use `headerBackgroundColor` for setting the header background
* You can use `headerTextStyle` for setting header text style including `color` property
* You can use `headerUnderlayColor` for setting header text underlay color 

Do try these out and let me know if helps. 
Also, it will be great if you can report other requirements/issues with this library. I will be happy to add/fix them for you :)
